version: '3.8'
services:
  postgres-db:
    container_name: oauth-demo-postgres-db
    image: postgres:14.3-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - 5440:5432
    environment:
      - POSTGRES_USER=demo
      - POSTGRES_PASSWORD=123

volumes:
  postgres_data:

networks:
  default:
    name: nest-oauth-google-demo
    driver: bridge